{% set name = "kuti" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b3aeeaa89b10b5e0e86d327912ac5256b894f1dc8d81de733e3baa355cbb10e4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.9
    - poetry
  run:
    - future
    - h5py >=2.10.0,<3.0.0
    - matplotlib-base
    - munch
    - numpy
    - opencv
    - pandas
    - pillow >=7,<8
    - python >=3.6,<3.9
    - scikit-image >=0.16.2,<0.17.0
    - scikit-learn >=0.22.1,<0.23.0
    - scipy
    - tensorflow

test:
  imports:
    - kuti

about:
  home: https://github.com/subpic/ku/tree/master
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Keras training management utilities.
  dev_url: https://github.com/subpic/ku/tree/master

extra:
  recipe-maintainers:
    - oblute
    - mxr-conda
